package upgrad;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;
import java.sql.*;

public class Driver {

    /**
     * Driver class main method
     * @param args
     * @throws SQLException
     */
    public static void main(String[] args) {

        // MySql credentials
        String sqlURL = "jdbc:mysql://pgc-sd-bigdata.cyaielc9bmnf.us-east-1.rds.amazonaws.com:3306/pgcdata";
        String sqlUserName = "student";
        String sqlPassword = "STUDENT123";

        //Mongo DB Configuration details
        String mongoDBName = "upgrad";
        String mongoConnectionString="mongodb+srv://admin:admin@cluster0.srxca.mongodb.net/upgrad?retryWrites=true&w=majority";
        String mongoCollectinName = "products";


        // Connection Default Value Initialization
        Connection sqlConnection = null;
        MongoClient mongoClient = null;

        try {

            // Initializing the Mongo DB connection
            mongoClient = MongoClients.create(mongoConnectionString);
            MongoDatabase db = mongoClient.getDatabase(mongoDBName);
            MongoCollection<Document> collection = db.getCollection(mongoCollectinName);

            //Verifying connection to Mongo DB established
            if(mongoClient!=null){
                System.out.println("Connected to Mongo DB successfully");
                System.out.println();
            }

            //Initializing the MySQL Connection
            sqlConnection = DriverManager.getConnection(sqlURL,sqlUserName,sqlPassword);
            Statement statement = sqlConnection.createStatement();

            //Verifying connection  to MySQL established
            if(sqlConnection!=null){
                System.out.println("Connected to MySQL DB successfully");
                System.out.println();
            }

            /**
             * Dropping the collection if already exist to avoid the duplicate import of data every time when code is run
             */
            db.getCollection(mongoCollectinName).drop();
            System.out.println("Existing collection " + mongoCollectinName + " dropped successfully");
            System.out.println();

            /**
             * Import data into MongoDB from MySQL
             *
             */

            //Import the data from MySQL Mobiles Table into Mongo DB products collection
            CRUDHelper.importDataIntoMongoDB(
                    sqlConnection,
                    statement,
                    "mobiles",
                    "Mobile",
                    collection
            );

            //Importing the data from MySQL Cameras table into Mongo DB products collection
            CRUDHelper.importDataIntoMongoDB(
                    sqlConnection,
                    statement,
                    "cameras",
                    "Camera",
                    collection
            );

            //Importing the data from MySQL Headphones table into Mongo DB products collection
            CRUDHelper.importDataIntoMongoDB(
                    sqlConnection,
                    statement,
                    "headphones",
                    "Headphone",
                    collection
            );

            // List all products in the inventory
            CRUDHelper.displayAllProducts(collection);

            // Display top 5 Mobiles
            CRUDHelper.displayTop5Mobiles(collection);

            // Display products ordered by their categories in Descending Order Without autogenerated Id
            CRUDHelper.displayCategoryOrderedProductsDescending(collection);

            // Display product count in each category
            CRUDHelper.displayProductCountByCategory(collection);

            // Display wired headphones
            CRUDHelper.displayWiredHeadphones(collection);
        }
        catch(Exception ex) {
            System.out.println("Got Exception.");
            ex.printStackTrace();
        }
        finally {
            // Close Connections
            try{
                if(sqlConnection!=null){
                    sqlConnection.close();
                    System.out.println();
                    System.out.println("MySQL DB connection closed successfully");
                    System.out.println();

                }

                if(mongoClient!=null){
                    mongoClient.close();
                    System.out.println("Mongo DB connection closed successfully");
                    System.out.println();
                }
            }
            catch(SQLException e){
                System.out.println("Got exception while closing the connection");
                e.printStackTrace();
            }
        }
    }
}